server:
  port: 8082

spring:
  application:
    name: ai-service
  profiles:
    active: @env@
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.202.140:8848
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY:sk-8fe45248b96e4780b6c48bf82cd78690}

