spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.202.140:8848
  data:
    redis:
      host: 192.168.202.140
      port: 6379
      database: 0
  datasource:
    url: jdbc:mysql://192.168.202.140:3306/luusmosh?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: Hhh001022..
    driver-class-name: com.mysql.cj.jdbc.Driver
