spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.202.140:8848
  datasource:
    url: jdbc:mysql://192.168.202.140:3306/luusmosh?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
